### ISSUE TITLE
problem about Data

### ISSUE THREAD

**Issue by Milleupup** [SajjadMzf/EarlyLCPred#3]
Thank you for sharing the code, but when I tried to reproduce it，it shows that KeyError: "Unable to open object (object 'state_data' doesn't exist)" which may come from  missing h5 file. Could you please provide the relevant h5 file or generated code under the RenderedDataset folder ?

**Comment by SajjadMzf** [comment]
Hello,
h5 files are the extracted features from the trajectory dataset.
You may preprocess and extract features (in order) using the following two repos:
https://github.com/SajjadMzf/TrajPreprocess/tree/b683fb8b27800e0202417865e05e192e7647cfa6
https://github.com/SajjadMzf/TrajFeatures/tree/7dd7bf3e699d1bf97cde3e7b10523682c810bbfc
